name: Build, Tag, and Release Docker Image

on:
  push:
    tags:
      - 'releases/*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version tag
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/releases/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yahoofinanceapi-wrapper:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/yahoofinanceapi-wrapper:${{ env.TAG_NAME }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: 'Release ${{ env.TAG_NAME }}'
          body: |
            Docker image published:
            - `latest`
            - `${{ env.TAG_NAME }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
